apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: <ingress-name>
  namespace: <namespace-name>
spec:
  entryPoints:
    - <port-name>
  routes:
    - match: HostSNI(`*`)
      services:
        - name: <service-name>
          port: <service-port>